server:
  port: 8200
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: cloud-stream
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/