server:
  port: 8071
eureka:
  instance:
    hostname: peer1
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://peer1:8061/eureka/
