server:
  port: 8087



spring:
  profiles:
    active: dev
  application:
    name: @artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.79.129
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0


security:
  oauth2:
    client:
      client-id: test
      client-secret: test1234
      registered-redirect-uri: http://mrbird.cc
