eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
spring:
  application:
    name: @artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jingnanfeng/application.git
          search-paths: cloud
          default-label: master
server:
  port: 8082