eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8084

spring:
  application:
    name: @artifactId@
zuul:
  routes:
    ##
    hello:
      path: /cloud-hello/**
      serviceId: privider-hello
    ##
    feign:
      path: /cloud-feign/**
      serviceId: service-feign
