server:
  port: 8084

spring:
  profiles:
    active: dev
  application:
    name: @artifactId@
  datasource:
    username: root
    password: root
  mail:
    host: smtp.163.com
    username: liu05265218@163.com
    password: nanfengbujing123
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://localhost:8100
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh